[package]
name = "logic-paint"
version = "0.1.0"
edition = "2018"
authors = ["Alec Thilenius <alec@thilenius.com>"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
arrayvec = { version = "0.7.1", features = ["serde"] }
base64 = "0.13.0"
bincode = "1.3.1"
console_error_panic_hook = { version = "0.1.6", optional = true }
generational-arena = "0.2.8"
glam = { version = "0.20.0", features = ["serde", "bytemuck"] }
js-sys = "0.3.55"
miniz_oxide = "0.4.4"
serde = "1.0.130"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3.55"
features = [
  "Document",
  "Element",
  "HtmlCanvasElement",
  "KeyboardEvent",
  "MessageChannel",
  "MessagePort",
  "MouseEvent",
  "Storage",
  "WebGl2RenderingContext",
  "WebGlBuffer",
  "WebGlProgram",
  "WebGlShader",
  "WebGlTexture",
  "WebGlUniformLocation",
  "WebGlVertexArrayObject",
  "WheelEvent",
  "Window",
  "console",
]
