[package]
name = "wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = [
  "common/web",
]

[dependencies]
common = { path="../common", default-features=false }
wasm-bindgen = "0.2"
bevy_webgl2 = "0.5"
